### ISSUE TITLE
transparent (automated) deployment? 

### ISSUE THREAD

**Issue by s-a** [mr-mig/going-to-production#6]
This is a very usefull resource.  
Should transparent deployment be automated? For example capistrano or Shipit with a possibility to rollback to previous versions?

**Comment by mr-mig** [comment]
Ideally yes, you want to have something like green-blue deployment: 
- https://martinfowler.com/bliki/BlueGreenDeployment.html
- https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html

**Comment by s-a** [comment]
I love these docs. I think those infos should be part of your list.

**Comment by mr-mig** [comment]
I will add those to useful resources list
